README.md, action.yml, scripts/main.sh, scripts/publish.sh, test/index.js
Yarn is now used for publishing rather than npm. This is required when using Yarn-specific dependency protocols such as `workspace:`, which Yarn will resolve before publishing.
The README has been updated to explain the assumptions of this action, and the example has been updated to match these assumptions.
=> Use Yarn for publishing rather than npm

action.yml
as part of our commitment to keeping our action consumption secure this has now been updated to be pinned to a `SHA` instead of a version tag
=> Use SHA instead of tag for action consumption

README.md, action.yml
The Slack announce feature has been reverted because it is a breaking change for repositories/organizations that use an action allowlist. It has been temporarily reverted, so that i can be republished in a new major version.
=> Revert slack accounce

README.md, action.yml
This reverts commit 27b09de1b68f71fbacb00faf68275feab24dadfa, restoring the Slack announce feature. The feature was temporarily reverted so that we could publish v2.1.1 without it.
=> Revert "Revert slack accounce (#22)"

README.md
The README has been updated to explain that we use this action, and that it must be listed as an allowed action in repositories/ organizations with restrictive action settings.
=> Document usage of `slackapi/slack-github-action`

action.yml, scripts/publish.sh
This pull request renames the `YARN_NPM_TAG` environment variable to `PUBLISH_NPM_TAG`. The reason for doing so is that
environment variables starting with `YARN_` are reserved for Yarn configuration options. Hence, if we use `YARN_NPM_TAG`
as an environment variable, it will cause Yarn to throw an error. On the other hand, `PUBLISH_NPM_TAG` is not
a reserved environment variable name, which makes it a preferred choice.
1. Rename `YARN_NPM_TAG` to `PUBLISH_NPM_TAG`.
=> Rename `YARN_NPM_TAG` to `PUBLISH_NPM_TAG`

scripts/publish.sh
Hi there!
I had an issue trying to this action with a private npm registry. I had to add a `.yarnrc.yml` file that contains the private scope & registry but the absence of .npmrc did not allow the action to correctly compare versions. This lead to errors because `npm` was not able to find the private module.
This PRs tries to fix this issue by migrating the comparison to `yarn`.
=> switch package version comparison to yarn

README.md, action.yml
I didn't think we could do this as i thought the bot was restricted to a single channel, but it turns out we can.
Consumers can use this if they wish to post to a channel other than the default.
=> Add new input to support customising the Slack channel

action.yml
I missed this. It's no big deal, but kinda pointless to run this step if the `name-version` and `slack` steps aren't run :upside_down_face:
=> only run `final-text` if `slack-webhook-url` is defined

action.yml
Okay! our deployment today failed to tag the subteam because I didn't have this configured properly. I had assumed the functionality for tagging individuals and subteams was identical, but I was wrong! see: https://api.slack.com/reference/surfaces/formatting#mentioning-groups
I've tested this out in a private channel in our Slack instance and it works properly:
=> Add functionality for subteams

scripts/publish.sh
This uses the `npm-tag` to check for the latest version of the package on NPM.
=> Use tag to check latest package version

.github/workflows/shellcheck.yml, .github/workflows/test-monorepo.yml, .github/workflows/test-polyrepo.yml, .github/workflows/test.yml
Currently, code is not automatically linted and tests are not automatically run on pull requests. This happens because the workflows which would perform these steps are not configured to run on pull requests but only on a push to `main`. This PR modifies the workflows to run on the `pull_request` event.
=> Run linting and testing GitHub workflows on PRs

action.yml
Typically, for a project, this action is run twice: once in dry-run mode (to allow approvers to review the package before it is published) and another time to issue the approval step and then actually publish the package.
When the action is run in dry-run mode, an announcement on Slack is created in order to notify approvers. If this fails in any way, however, it halts the release workflow completely and prevents the second instance of the action from running. This means that the package can never be released automatically and must be released manually.
This commit fixes this problem by instructing GitHub Actions that it is not mandatory for the Slack announcement step to pass in order for the release workflow to continue.
---
You can see a test for this change on a fork here: …
=> Don't fail overall if Slack announcement fails

action.yml
We have found that the Slack announcement does not work correctly for public channels when the `channel` parameter is given. The action has been updated to omit the default if no channel is specified, so that announcements to `metamask-dev` work correctly.
=> remove default channel

CHANGELOG.md, action.yml, package.json
- Fix Slack announcement for public default channel ([#73](https://github.com/MetaMask/action-npm-publish/pull/73))
- We have found that the Slack announcement does not work correctly for public channels when the `channel` parameter is given. The action has been updated to omit the default if no channel is specified, so that announcements to the default channel work correctly even if it is public.
=> Release 4.0.3

action.yml
The action manifest used the id `slack` for two steps, which is not allowed. We don't reference this id anywhere, so it has been removed.
=> fix: Fix action manifest validation error

CHANGELOG.md, package.json
The v5.0.1 release was back ported to the `v5.0.x` branch. This PR updates the main branch with that version bump and changelog entry.
=> Update version and changelog with v5.0.1 release

action.yml
Following recent changes it was no longer possible to use this action with a non-default Slack channel as the target for the messages.
Any attempt to use the action would fail with: `Error: Need to provide at least one botToken or webhookUrl`
This PR fixes this by re-adding the required configuration to the action.
=> fix: add missing configuration for non-default Slack channel messages

.github/workflows/test-monorepo.yml, scripts/main.sh, scripts/publish.sh
closes #58 
this will also ensure reports are only generated for packages that have changes
=> Only show packages in the dry run that need publishing

scripts/report.sh
`pkdiff` throws an error if the package is not published:
```
@ts-bridge/resolver
@ts-bridge/resolver@latest: downloading...
Error: Download failed: @ts-bridge/resolver@latest from registry: https://registry.npmjs.org/
at /usr/local/lib/node_modules/pkdiff/src/compare.js:188:15
```
This makes it return with exit code 1, causing the publish to fail. As as simple workaround I've added `|| true`, which always returns exit code 0.
=> Fix report script for unpublished packages

scripts/main.sh
The original intent was to _only_ `set -x` when in debug environments, but instead we were setting it if `ACTIONS_RUNNER_DEBUG` was unset... so effectively all non-debug environments. This change remedies that mistake.
=> Disable debug output in non-debug environments

scripts/report.sh
=> Fix backwards diff
